import Link from 'next/link'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Privacy Policy | Next Level Soccer SF',
  description: 'How Next Level Soccer SF collects, uses, and protects your information.',
}

export default function PrivacyPolicyPage() {
  return (
    <>
      <Navbar />
      <main className="bg-[#f7f2e8] min-h-screen pt-24 pb-16 px-4 sm:px-6">
        <article className="max-w-3xl mx-auto">
          <Link
            href="/"
            className="inline-flex items-center gap-1 text-sm font-semibold text-[#f05a28] hover:text-[#d94e21] mb-8"
          >
            ← Back to Home
          </Link>

          <header className="mb-10">
            <p className="text-xs font-semibold uppercase tracking-widest text-[#f05a28] mb-2">Legal</p>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-[#062744] leading-tight">Privacy Policy</h1>
            <p className="text-sm text-slate-500 mt-3">Next Level Soccer San Francisco (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;)</p>
            <p className="text-sm text-slate-600 mt-2">
              <strong className="text-[#062744]">Last updated:</strong> May 2026
            </p>
          </header>

          <div className="bg-white border border-[#e8d8ce] rounded-2xl p-6 sm:p-10 shadow-sm space-y-8 text-slate-700 text-[15px] sm:text-base leading-relaxed">
            <section className="space-y-3">
              <h2 className="text-xl font-bold text-[#062744]">1. Introduction</h2>
              <p>
                This Privacy Policy describes how Next Level Soccer SF collects, uses, stores, and protects information when you use
                our website, register for camps, sign in with Google, or interact with our services. By using our site or submitting
                information, you agree to this policy. If you do not agree, please do not use our services.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-bold text-[#062744]">2. Information we collect</h2>
              <p className="font-semibold text-[#062744]">Parent and guardian contact information</p>
              <p>
                When you create an account, register for camp, or contact us, we may collect your name, email address, and phone
                number. If you choose <strong>Google Sign-In</strong> (Single Sign-On), Google may share your name, email address,
                and profile information with us according to Google&apos;s own policies. We use this information to communicate
                about registration, payments, schedules, and camp operations.
              </p>
              <p className="font-semibold text-[#062744] pt-2">Player and camper information</p>
              <p>
                Our registration forms collect information necessary to run safe, age-appropriate programs. This may include the
                player&apos;s name, date of birth, gender (where collected for program grouping), school and grade, soccer club,
                playing level, shirt size, camp week selections, emergency contacts, medical notes you choose to provide, and{' '}
                <strong>optional profile photographs</strong>. We also store <strong>internal coaching evaluations</strong> and
                report-card style assessments generated by our staff to track development and communicate progress to families where
                applicable.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-bold text-[#062744]">3. How we use your information</h2>
              <ul className="list-disc pl-5 space-y-2 marker:text-[#f05a28]">
                <li>To process registrations, waitlists, and payments instructions you receive from us</li>
                <li>To operate camps, assign groups, and maintain safety and emergency contact records</li>
                <li>To send service-related emails (for example, registration confirmations, schedule updates, or coach feedback)</li>
                <li>To maintain our coach portal and internal tools used by authorized staff only</li>
                <li>To comply with law or protect the rights, safety, and integrity of our participants and organization</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-bold text-[#062744]">4. Cookies and authentication (Supabase)</h2>
              <p>
                We use <strong>Supabase</strong> for authentication and secure storage of account sessions. Supabase and our
                application may set <strong>cookies</strong> or similar technologies in your browser to keep you signed in, protect
                against abuse, and maintain session security. These cookies are used for authentication and core site functionality,
                not for advertising retargeting by us.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-bold text-[#062744]">5. Where data is stored and service providers</h2>
              <p>
                We use trusted service providers to host our website and store data, including <strong>Supabase</strong> (database and
                authentication) and email delivery providers as configured for our organization. These providers process data on our
                behalf under their respective terms and security practices. We do not authorize them to use your personal information
                for their own marketing purposes.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-bold text-[#062744]">6. Sale of data</h2>
              <p>
                <strong>We do not sell your personal information</strong> to third parties. We do not share your information for
                cross-context behavioral advertising as a &quot;sale&quot; of personal data.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-bold text-[#062744]">7. Children&apos;s information</h2>
              <p>
                Our programs serve youth participants. Personal information about children is provided by parents or legal guardians
                through our registration process. If you believe we have received information about a child in error, please contact us
                and we will take appropriate steps.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-bold text-[#062744]">8. Data retention and security</h2>
              <p>
                We retain information for as long as needed to operate our programs, meet legal obligations, resolve disputes, and
                enforce our agreements. We use administrative, technical, and organizational measures designed to protect information
                against unauthorized access, loss, or misuse. No method of transmission over the Internet is completely secure.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-bold text-[#062744]">9. Your choices and rights</h2>
              <p>
                Depending on where you live, you may have rights to access, correct, or delete certain personal information, or to
                object to or restrict certain processing. To make a request, contact us using the email below. We may need to verify
                your identity before responding.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-bold text-[#062744]">10. Changes to this policy</h2>
              <p>
                We may update this Privacy Policy from time to time. We will post the revised policy on this page and update the
                &quot;Last updated&quot; date above. Continued use of our services after changes constitutes acceptance of the updated
                policy, to the extent permitted by law.
              </p>
            </section>

            <section className="space-y-3 border-t border-[#e8d8ce] pt-8">
              <h2 className="text-xl font-bold text-[#062744]">11. Contact us</h2>
              <p>
                Questions about this Privacy Policy or our practices:{' '}
                <a
                  href="mailto:nextlevelsoccersf@gmail.com"
                  className="font-semibold text-[#f05a28] hover:text-[#d94e21] underline underline-offset-2"
                >
                  nextlevelsoccersf@gmail.com
                </a>
              </p>
            </section>
          </div>
        </article>
      </main>
      <Footer />
    </>
  )
}
